web: gunicorn ProjectManagement.wsgi --bind 0.0.0.0:$PORT --workers 4 --threads 4 --worker-class gthread --timeout 120 --log-level info
release: python manage.py migrate && python manage.py collectstatic --noinput
worker: celery -A ProjectManagement worker --pool=threads --concurrency=4 -l info -Q celery,email,slack