release: python manage.py migrate
web: gunicorn ProjectManagement.wsgi --bind 0.0.0.0:$PORT --workers 8 --threads 2 --worker-class gthread --timeout 120 --log-level info
worker: celery -A ProjectManagement worker --pool=threads --concurrency=2 -l info -Q celery,email,slack
